# Book settings
title: Herramientas estadísticas para la investigación
author: Pablo Huijse and Eliana Scheihing 
logo: logo.png
only_build_toc_files: true
exclude_patterns : [_build, "**.ipynb_checkpoints"]

execute:
  execute_notebooks: 'off'
  allow_errors: true
  timeout: 360


repository:
  url: https://github.com/magister-informatica-uach/INFO337

html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  only_build_toc_files: true

sphinx:
  config:
    html_show_copyright: false
    language: es
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    myst_enable_extensions: 
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - html_admonition

latex:
  latex_documents:
    targetname: book.tex
